<?php
date_default_timezone_set('Asia/Jakarta');
include '../config.php';
global $conn;

if(!isset($_SESSION['admin'])){
    header("Location: login.php");
    exit;
}

// Flash message
$flash = $_SESSION['flash'] ?? null;
unset($_SESSION['flash']);

// ============================================
// EXPORT HANDLER (Before any output)
// ============================================
if(isset($_GET['export'])){
    $exportType = $_GET['export'];
    $exportStatus = $_GET['status'] ?? '';
    $exportBarber = $_GET['barber'] ?? '';
    $exportTanggal = $_GET['tanggal'] ?? '';
    $exportSearch = $_GET['search'] ?? '';
    
    $exportQuery = "
    SELECT b.*, u.username, u.email, u.phone, u.gender, 
           p.nama_paket, p.harga, bar.nama as barber_nama
    FROM booking b
    LEFT JOIN users u ON b.user_id = u.id
    JOIN paket p ON b.paket_id = p.id
    JOIN barber bar ON b.barber_id = bar.id
    WHERE 1
    ";
    
    // Match display filter logic exactly
    if($exportStatus === '' || $exportStatus === 'all'){
        // Default: hide expired unless 'all' explicitly selected
        if($exportStatus !== 'all'){
            $exportQuery .= " AND b.status != 'expired'";
        }
    } else {
        $exportQuery .= " AND b.status='".mysqli_real_escape_string($conn, $exportStatus)."'";
    }

    if($exportBarber) $exportQuery .= " AND b.barber_id='".mysqli_real_escape_string($conn, $exportBarber)."'";
    if($exportTanggal) $exportQuery .= " AND b.tanggal='".mysqli_real_escape_string($conn, $exportTanggal)."'";
    if($exportSearch){
        $se = mysqli_real_escape_string($conn, $exportSearch);
        $exportQuery .= " AND (u.username LIKE '%$se%' OR p.nama_paket LIKE '%$se%' OR bar.nama LIKE '%$se%')";
    }
    
    $exportQuery .= " ORDER BY b.tanggal DESC, b.jam ASC";
    $exportResult = mysqli_query($conn, $exportQuery);
    
    if($exportType === 'excel'){
        header('Content-Type: application/vnd.ms-excel; charset=utf-8');
        header('Content-Disposition: attachment; filename="HostelBarbershop_Booking_Report_'.date('Y-m-d_His').'.xls"');
        
        echo '<!DOCTYPE html>
        <html>
        <head>
        <meta charset="UTF-8">
        <style>
        body{font-family:Calibri,Arial,sans-serif;background:#f5f5f5;margin:0;padding:20px;}
        .header{background:#1a1a1a;color:white;padding:25px;text-align:center;border-radius:8px 8px 0 0;}
        .header h1{font-size:28px;margin:0;letter-spacing:2px;}
        .header p{color:#aaa;font-size:12px;margin:5px 0 0;}
        .meta-box{background:#fff;border:1px solid #ddd;padding:15px;margin:15px 0;border-radius:6px;}
        .meta-box table{width:100%;font-size:12px;}
        .meta-box td{padding:4px 10px;}
        .meta-box td:first-child{font-weight:bold;color:#555;width:120px;}
        table.data{width:100%;border-collapse:collapse;background:#fff;border-radius:6px;overflow:hidden;}
        table.data th{background:#1a1a1a;color:#fff;padding:12px;font-size:11px;text-transform:uppercase;letter-spacing:0.5px;border:1px solid #333;}
        table.data td{padding:10px;border:1px solid #e0e0e0;font-size:12px;vertical-align:middle;}
        table.data tr:nth-child(even){background:#f9f9f9;}
        .status-paid{background:#d4edda!important;color:#155724;font-weight:bold;}
        .status-pending{background:#fff3cd!important;color:#856404;font-weight:bold;}
        .status-expired{background:#f8d7da!important;color:#721c24;font-weight:bold;}
        .price{font-weight:bold;color:#1a1a1a;}
        .summary{background:#1a1a1a;color:#fff;padding:20px;border-radius:6px;margin-top:15px;display:flex;justify-content:space-around;text-align:center;}
        .summary-item h3{font-size:20px;margin:0 0 5px;}
        .summary-item p{font-size:10px;text-transform:uppercase;letter-spacing:1px;opacity:0.7;margin:0;}
        .footer{text-align:center;color:#999;font-size:11px;margin-top:20px;padding-top:15px;border-top:1px solid #ddd;}
        .badge{display:inline-block;padding:3px 10px;border-radius:20px;font-size:10px;font-weight:bold;text-transform:uppercase;}
        .no{text-align:center;color:#999;font-style:italic;padding:40px;}
        </style>
        </head>
        <body>';
        
        echo '<div class="header">';
        echo '<h1>HOSTEL BARBERSHOP</h1>';
        echo '<p>Booking Report &bull; '.date('d F Y H:i:s').' &bull; Generated by Admin</p>';
        echo '</div>';
        
        echo '<div class="meta-box">';
        echo '<table>';
        echo '<tr><td>Status Filter</td><td>: '.($exportStatus ? ucfirst($exportStatus) : 'Active (Hide Expired)').'</td><td>Barber Filter</td><td>: '.($exportBarber ? 'ID #'.$exportBarber : 'All Barbers').'</td></tr>';
        echo '<tr><td>Date Filter</td><td>: '.($exportTanggal ? date('d M Y', strtotime($exportTanggal)) : 'All Dates').'</td><td>Search</td><td>: '.($exportSearch ? $exportSearch : 'None').'</td></tr>';
        echo '<tr><td>Total Records</td><td>: '.mysqli_num_rows($exportResult).' bookings</td><td>Report Time</td><td>: '.date('H:i:s').'</td></tr>';
        echo '</table>';
        echo '</div>';
        
        echo '<table class="data">';
        echo '<tr>
            <th style="width:40px;">No</th>
            <th style="width:60px;">Booking ID</th>
            <th>Customer</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Gender</th>
            <th>Package</th>
            <th style="width:90px;">Price</th>
            <th>Barber</th>
            <th style="width:90px;">Date</th>
            <th style="width:60px;">Time</th>
            <th style="width:80px;">Status</th>
            <th>Booked At</th>
        </tr>';
        
        $paidCount = 0; $pendingCount = 0; $expiredCount = 0; $totalPaid = 0; $no = 1;
        
        if(mysqli_num_rows($exportResult) > 0){
            mysqli_data_seek($exportResult, 0);
            while($row = mysqli_fetch_assoc($exportResult)){
                if($row['status']=='paid'){ $totalPaid += $row['harga']; $paidCount++; }
                elseif($row['status']=='pending') $pendingCount++;
                else $expiredCount++;
                
                $statusClass = 'status-'.$row['status'];
                $badgeColor = $row['status']=='paid' ? '#28a745' : ($row['status']=='pending' ? '#ffc107' : '#dc3545');
                $badgeText = $row['status']=='pending' ? '#000' : '#fff';
                
                echo '<tr class="'.$statusClass.'">';
                echo '<td style="text-align:center;">'.$no++.'</td>';
                echo '<td style="text-align:center;font-weight:bold;">#'.$row['id'].'</td>';
                echo '<td>'.$row['username'].'</td>';
                echo '<td>'.$row['email'].'</td>';
                echo '<td>'.$row['phone'].'</td>';
                echo '<td>'.$row['gender'].'</td>';
                echo '<td>'.$row['nama_paket'].'</td>';
                echo '<td class="price">Rp'.number_format($row['harga']).'</td>';
                echo '<td>'.$row['barber_nama'].'</td>';
                echo '<td>'.date('d M Y', strtotime($row['tanggal'])).'</td>';
                echo '<td>'.$row['jam'].'</td>';
                echo '<td style="text-align:center;"><span class="badge" style="background:'.$badgeColor.';color:'.$badgeText.';">'.strtoupper($row['status']).'</span></td>';
                echo '<td>'.$row['created_at'].'</td>';
                echo '</tr>';
            }
        } else {
            echo '<tr><td colspan="13" class="no">No bookings found for selected filters</td></tr>';
        }
        
        echo '</table>';
        
        echo '<div class="summary">';
        echo '<div class="summary-item"><h3>'.$paidCount.'</h3><p>Paid Bookings</p></div>';
        echo '<div class="summary-item"><h3>'.$pendingCount.'</h3><p>Pending</p></div>';
        echo '<div class="summary-item"><h3>'.$expiredCount.'</h3><p>Expired</p></div>';
        echo '<div class="summary-item"><h3>Rp'.number_format($totalPaid).'</h3><p>Total Revenue</p></div>';
        echo '</div>';
        
        echo '<div class="footer">&copy; Hostel Barbershop Management System &bull; Confidential Report</div>';
        echo '</body></html>';
        exit;
    }
    
    if($exportType === 'pdf'){
        header('Content-Type: text/html; charset=utf-8');
        
        echo '<!DOCTYPE html>
        <html>
        <head>
        <meta charset="UTF-8">
        <title>Hostel Barbershop Booking Report</title>
        <style>
        @page { size: A4 landscape; margin: 12mm; }
        *{margin:0;padding:0;box-sizing:border-box;}
        body{font-family:"Segoe UI",Arial,sans-serif;font-size:10px;line-height:1.4;color:#333;background:#f5f5f5;padding:15px;}
        .page{width:100%;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 10px rgba(0,0,0,0.1);}
        .header{text-align:center;padding:20px;background:#1a1a1a;color:#fff;}
        .header h1{font-size:22px;letter-spacing:3px;margin:0;}
        .header p{color:#aaa;font-size:11px;margin-top:5px;}
        .meta-box{background:#f8f9fa;border:1px solid #dee2e6;padding:12px;margin:15px;border-radius:6px;}
        .meta-box table{width:100%;font-size:10px;}
        .meta-box td{padding:3px 8px;}
        .meta-box td:first-child{font-weight:bold;color:#495057;width:100px;}
        table.data{width:100%;border-collapse:collapse;margin:15px;}
        table.data th{background:#1a1a1a;color:#fff;padding:8px;font-size:9px;text-transform:uppercase;letter-spacing:0.5px;border:1px solid #333;text-align:left;}
        table.data td{padding:8px;border:1px solid #dee2e6;font-size:10px;vertical-align:middle;}
        table.data tr:nth-child(even){background:#f8f9fa;}
        .status-paid{background:#d4edda!important;color:#155724;font-weight:bold;}
        .status-pending{background:#fff3cd!important;color:#856404;font-weight:bold;}
        .status-expired{background:#f8d7da!important;color:#721c24;font-weight:bold;}
        .price{font-weight:bold;color:#1a1a1a;}
        .summary{background:#1a1a1a;color:#fff;padding:15px;margin:15px;border-radius:6px;display:flex;justify-content:space-around;text-align:center;}
        .summary-item h3{font-size:16px;margin:0 0 3px;}
        .summary-item p{font-size:9px;text-transform:uppercase;letter-spacing:1px;opacity:0.8;margin:0;}
        .footer{text-align:center;color:#6c757d;font-size:9px;margin:15px;padding-top:10px;border-top:1px solid #dee2e6;}
        .badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:9px;font-weight:bold;text-transform:uppercase;}
        .no{text-align:center;color:#999;font-style:italic;padding:30px;}
        .contact-info{color:#666;font-size:9px;}
        </style>
        </head>
        <body>
        <div class="page">';
        
        echo '<div class="header">';
        echo '<h1>HOSTEL BARBERSHOP</h1>';
        echo '<p>Booking Report &bull; '.date('d F Y').' &bull; Generated by Admin</p>';
        echo '</div>';
        
        echo '<div class="meta-box">';
        echo '<table>';
        echo '<tr><td>Status Filter</td><td>: '.($exportStatus ? ucfirst($exportStatus) : 'Active (Hide Expired)').'</td><td>Barber Filter</td><td>: '.($exportBarber ? 'ID #'.$exportBarber : 'All Barbers').'</td></tr>';
        echo '<tr><td>Date Filter</td><td>: '.($exportTanggal ? date('d M Y', strtotime($exportTanggal)) : 'All Dates').'</td><td>Search</td><td>: '.($exportSearch ? $exportSearch : 'None').'</td></tr>';
        echo '<tr><td>Total Records</td><td>: '.mysqli_num_rows($exportResult).' bookings</td><td>Report Time</td><td>: '.date('H:i:s').'</td></tr>';
        echo '</table>';
        echo '</div>';
        
        echo '<table class="data">';
        echo '<tr>
            <th style="width:30px;">No</th>
            <th style="width:50px;">ID</th>
            <th>Customer</th>
            <th>Contact</th>
            <th>Package</th>
            <th style="width:80px;">Price</th>
            <th>Barber</th>
            <th style="width:80px;">Date</th>
            <th style="width:50px;">Time</th>
            <th style="width:70px;">Status</th>
            <th style="width:90px;">Booked At</th>
        </tr>';
        
        $paidCount = 0; $pendingCount = 0; $expiredCount = 0; $totalPaid = 0; $no = 1;
        
        if(mysqli_num_rows($exportResult) > 0){
            mysqli_data_seek($exportResult, 0);
            while($row = mysqli_fetch_assoc($exportResult)){
                if($row['status']=='paid'){ $totalPaid += $row['harga']; $paidCount++; }
                elseif($row['status']=='pending') $pendingCount++;
                else $expiredCount++;
                
                echo '<tr class="status-'.$row['status'].'">';
                echo '<td style="text-align:center;">'.$no++.'</td>';
                echo '<td style="text-align:center;">#'.$row['id'].'</td>';
                echo '<td>'.$row['username'].'<<br><span class="contact-info">'.$row['gender'].'</span></td>';
                echo '<td>'.$row['email'].'<<br><span class="contact-info">'.$row['phone'].'</span></td>';
                echo '<td>'.$row['nama_paket'].'</td>';
                echo '<td class="price">Rp'.number_format($row['harga']).'</td>';
                echo '<td>'.$row['barber_nama'].'</td>';
                echo '<td>'.date('d M Y', strtotime($row['tanggal'])).'</td>';
                echo '<td>'.$row['jam'].'</td>';
                echo '<td style="text-align:center;"><span class="badge" style="background:'.($row['status']=='paid'?'#28a745':($row['status']=='pending'?'#ffc107':'#dc3545')).';color:'.($row['status']=='pending'?'#000':'#fff').';">'.strtoupper($row['status']).'</span></td>';
                echo '<td>'.$row['created_at'].'</td>';
                echo '</tr>';
            }
        } else {
            echo '<tr><td colspan="11" class="no">No bookings found for selected filters</td></tr>';
        }
        
        echo '</table>';
        
        echo '<div class="summary">';
        echo '<div class="summary-item"><h3>'.$paidCount.'</h3><p>Paid Bookings</p></div>';
        echo '<div class="summary-item"><h3>'.$pendingCount.'</h3><p>Pending</p></div>';
        echo '<div class="summary-item"><h3>'.$expiredCount.'</h3><p>Expired</p></div>';
        echo '<div class="summary-item"><h3>Rp'.number_format($totalPaid).'</h3><p>Total Revenue</p></div>';
        echo '</div>';
        
        echo '<div class="footer">&copy; Hostel Barbershop Management System &bull; Confidential Report</div>';
        echo '</div></body></html>';
        exit;
    }
}

// ============================================
// FILTERS & PAGINATION
// ============================================
$status = $_GET['status'] ?? '';
$barber = $_GET['barber'] ?? '';
$tanggal = $_GET['tanggal'] ?? '';
$search = $_GET['search'] ?? '';
$sort = $_GET['sort'] ?? 'tanggal';
$order = $_GET['order'] ?? 'DESC';
$page = max(1, intval($_GET['page'] ?? 1));
$perPage = 10;
$offset = ($page - 1) * $perPage;

// Validate sort
$allowedSort = ['id', 'tanggal', 'jam', 'status', 'username', 'nama_paket', 'barber_nama', 'harga'];
if(!in_array($sort, $allowedSort)) $sort = 'tanggal';
$order = strtoupper($order) === 'ASC' ? 'ASC' : 'DESC';

// Base query
$query = "
SELECT SQL_CALC_FOUND_ROWS
    b.*, u.username, u.photo as user_photo, u.email, u.phone, u.gender,
    p.nama_paket, p.harga,
    bar.nama as barber_nama, bar.foto as barber_foto,
    (SELECT COUNT(*) FROM barbershop_rating br WHERE br.user_id = b.user_id) as has_rating
FROM booking b
LEFT JOIN users u ON b.user_id = u.id
JOIN paket p ON b.paket_id = p.id
JOIN barber bar ON b.barber_id = bar.id
WHERE 1
";

// Apply filters - FIX: "all" status shows everything including expired
if($status === '' || $status === 'all'){
    // Default: show all except expired unless explicitly requested
    if($status !== 'all'){
        $query .= " AND b.status != 'expired'";
    }
} else {
    $query .= " AND b.status='".mysqli_real_escape_string($conn, $status)."'";
}

if($barber !== ''){
    $query .= " AND b.barber_id='".mysqli_real_escape_string($conn, $barber)."'";
}
if($tanggal !== ''){
    $query .= " AND b.tanggal='".mysqli_real_escape_string($conn, $tanggal)."'";
}
if($search !== ''){
    $searchEscaped = mysqli_real_escape_string($conn, $search);
    $query .= " AND (u.username LIKE '%$searchEscaped%' OR p.nama_paket LIKE '%$searchEscaped%' OR bar.nama LIKE '%$searchEscaped%')";
}

$query .= " ORDER BY ".mysqli_real_escape_string($conn, $sort)." $order";
$query .= " LIMIT $offset, $perPage";

$q = mysqli_query($conn, $query);
$totalResult = mysqli_query($conn, "SELECT FOUND_ROWS() as total");
$totalRows = mysqli_fetch_assoc($totalResult)['total'];
$totalPages = ceil($totalRows / $perPage);

// Stats - Revenue only
$statsQuery = "
SELECT 
    SUM(CASE WHEN status='paid' THEN p.harga ELSE 0 END) as revenue
FROM booking b
JOIN paket p ON b.paket_id = p.id
WHERE 1
";
if($status !== '' && $status !== 'all') $statsQuery .= " AND b.status='".mysqli_real_escape_string($conn, $status)."'";
if($barber !== '') $statsQuery .= " AND b.barber_id='".mysqli_real_escape_string($conn, $barber)."'";
if($tanggal !== '') $statsQuery .= " AND b.tanggal='".mysqli_real_escape_string($conn, $tanggal)."'";
if($search !== ''){
    $se = mysqli_real_escape_string($conn, $search);
    $statsQuery .= " AND EXISTS (SELECT 1 FROM users u2 WHERE u2.id=b.user_id AND u2.username LIKE '%$se%')";
}

$statsResult = mysqli_query($conn, $statsQuery);
$stats = mysqli_fetch_assoc($statsResult);

// Barber list for filter
$dataBarber = mysqli_query($conn, "SELECT * FROM barber ORDER BY nama ASC");

// ============================================
// TODAY'S SCHEDULE - AJAX Handler
// ============================================
if(isset($_GET['ajax_schedule']) && isset($_GET['schedule_date'])){
    $activeDate = $_GET['schedule_date'];
    
    // Get jadwal from DB
    $jadwal = [];
    $qJadwal = mysqli_query($conn, "SELECT * FROM jadwal_barber");
    while($j = mysqli_fetch_assoc($qJadwal)){
        $jadwal[] = $j['tanggal']."_".$j['barber_id'];
    }
    
    // Get all barbers
    $allBarbers = mysqli_query($conn, "SELECT id, nama, foto FROM barber ORDER BY nama ASC");
    
    $output = '';
    $hasAnySchedule = false;
    
    while($barberRow = mysqli_fetch_assoc($allBarbers)){
        $bid = $barberRow['id'];
        $key = $activeDate."_".$bid;
        $isOnDuty = in_array($key, $jadwal);
        
        // Get bookings for this barber on this date
        $bookingsQuery = "
            SELECT b.*, u.username, p.nama_paket, p.harga
            FROM booking b
            JOIN users u ON b.user_id = u.id
            JOIN paket p ON b.paket_id = p.id
            WHERE b.barber_id = $bid AND b.tanggal = '$activeDate' AND b.status = 'paid'
            ORDER BY b.jam ASC
        ";
        $bookingsResult = mysqli_query($conn, $bookingsQuery);
        $hasBookings = mysqli_num_rows($bookingsResult) > 0;
        
        // ONLY SHOW BARBER THAT IS ON DUTY
        if(!$isOnDuty) continue;
        
        $hasAnySchedule = true;
        
        $output .= '<div class="schedule-barber-card" data-date="'.$activeDate.'">';
        $output .= '<div class="schedule-barber-header">';
        $output .= '<div class="schedule-barber-avatar">';
        if(!empty($barberRow['foto'])){
            $output .= '<img src="upload/'.$barberRow['foto'].'" alt="'.htmlspecialchars($barberRow['nama']).'">';
        } else {
            $output .= strtoupper(substr($barberRow['nama'],0,1));
        }
        $output .= '</div>';
        $output .= '<div class="schedule-barber-info">';
        $output .= '<div class="schedule-barber-name">'.htmlspecialchars($barberRow['nama']).'</div>';
        $output .= '<div class="schedule-barber-role">On Duty</div>';
        $output .= '</div>';
        $output .= '<span class="schedule-barber-status status-on">Available</span>';
        $output .= '</div>';
        $output .= '<div class="schedule-barber-body">';
        
        if($hasBookings){
            $output .= '<div class="schedule-slots">';
            while($bk = mysqli_fetch_assoc($bookingsResult)){
                $output .= '<div class="schedule-slot slot-booked">';
                $output .= '<i class="fas fa-check-circle" style="margin-right:4px;"></i>';
                $output .= substr($bk['jam'], 0, 5).' - '.htmlspecialchars($bk['username']);
                $output .= '</div>';
            }
            $output .= '</div>';
        } else {
            $output .= '<div class="schedule-slots">';
            $output .= '<div class="slot-empty">No bookings yet - Available for walk-in</div>';
            $output .= '</div>';
        }
        
        $output .= '</div></div>';
    }
    
    if(!$hasAnySchedule){
        $output .= '<div style="grid-column:1/-1;text-align:center;padding:40px;color:var(--text-muted);">';
        $output .= '<i class="fas fa-calendar-day" style="font-size:48px;margin-bottom:16px;display:block;opacity:0.5;"></i>';
        $output .= '<h3 style="font-family:\'Space Grotesk\',sans-serif;font-size:18px;color:var(--text-secondary);margin-bottom:8px;">No barbers on duty</h3>';
        $output .= '<p>No barbers are scheduled for '.date('d M Y', strtotime($activeDate)).'.</p>';
        $output .= '</div>';
    }
    
    echo $output;
    exit;
}

// ============================================
// BOOKING DETAIL - AJAX Handler
// ============================================
if(isset($_GET['ajax_detail'])){
    $detailId = intval($_GET['ajax_detail']);

    $detailQuery = "
    SELECT b.*, u.username, u.email, u.phone, u.gender, u.photo as user_photo,
           p.nama_paket, p.harga,
           bar.nama as barber_nama, bar.foto as barber_foto
    FROM booking b
    LEFT JOIN users u ON b.user_id = u.id
    JOIN paket p ON b.paket_id = p.id
    JOIN barber bar ON b.barber_id = bar.id
    WHERE b.id = $detailId
    LIMIT 1
    ";

    $detailResult = mysqli_query($conn, $detailQuery);

    if(mysqli_num_rows($detailResult) > 0){
        $detail = mysqli_fetch_assoc($detailResult);
        header('Content-Type: application/json');
        echo json_encode([
            'id' => $detail['id'],
            'status' => $detail['status'],
            'username' => $detail['username'] ?? 'Deleted User',
            'email' => $detail['email'] ?? 'N/A',
            'phone' => $detail['phone'] ?? 'N/A',
            'gender' => $detail['gender'] ?? 'N/A',
            'nama_paket' => $detail['nama_paket'],
            'harga' => $detail['harga'],
            'harga_formatted' => number_format($detail['harga']),
            'barber_nama' => $detail['barber_nama'],
            'tanggal' => $detail['tanggal'],
            'tanggal_formatted' => date('d M Y', strtotime($detail['tanggal'])),
            'jam' => substr($detail['jam'], 0, 5),
            'created_at' => $detail['created_at'],
            'user_photo' => $detail['user_photo'],
            'barber_foto' => $detail['barber_foto']
        ]);
    } else {
        header('Content-Type: application/json');
        echo json_encode(['error' => 'Booking not found']);
    }
    exit;
}

// ============================================
// TODAY'S SCHEDULE - Default View
// ============================================
$dates = [];
$now = time();
$today = date('Y-m-d', $now);
$activeScheduleDate = $_GET['schedule_date'] ?? $today;

for($i = 0; $i < 7; $i++){
    $timestamp = strtotime("+$i day", $now);
    $date = date('Y-m-d', $timestamp);
    $diff = $i;
    
    $dates[] = [
        'full' => $date,
        'day'  => date('l', $timestamp),
        'show' => date('d M Y', $timestamp),
        'diff' => $diff,
        'is_today' => ($i === 0)
    ];
}

// Get jadwal from DB
$jadwal = [];
$qJadwal = mysqli_query($conn, "SELECT * FROM jadwal_barber");
while($j = mysqli_fetch_assoc($qJadwal)){
    $jadwal[] = $j['tanggal']."_".$j['barber_id'];
}

// Get all barbers
$allBarbers = mysqli_query($conn, "SELECT id, nama, foto FROM barber ORDER BY nama ASC");

function sortIcon($col, $currentSort, $currentOrder) {
    if($col !== $currentSort) return '<i class="fas fa-sort"></i>';
    return $currentOrder === 'ASC' ? '<i class="fas fa-sort-up"></i>' : '<i class="fas fa-sort-down"></i>';
}
?>

<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manage Bookings | Barber Management</title>

    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

    <style>
    :root{
        --bg-primary:#0d0d0d;
        --bg-secondary:#141414;
        --bg-tertiary:#1a1a1a;
        --bg-card:#1e1e1e;
        --bg-input:#181818;
        --bg-hover:#252525;
        --border:#333333;
        --border-light:#444444;
        --border-focus:#666666;
        --text-primary:#ffffff;
        --text-secondary:#c0c0c0;
        --text-muted:#777777;
        --accent:#ffffff;
        --danger:#ff4444;
        --danger-hover:#ff2222;
        --danger-soft:rgba(255,68,68,0.1);
        --success:#00ff88;
        --success-soft:rgba(0,255,136,0.1);
        --warning:#ffaa00;
        --warning-soft:rgba(255,170,0,0.1);
        --info:#4488ff;
        --info-soft:rgba(68,136,255,0.1);
        --gold:#ffd700;
        --gold-soft:rgba(255,215,0,0.1);
        --shadow:0 4px 24px rgba(0,0,0,0.5);
        --shadow-hover:0 8px 40px rgba(0,0,0,0.6);
        --radius:18px;
        --radius-sm:12px;
        --radius-xs:8px;
        --transition:all 0.3s cubic-bezier(0.4,0,0.2,1);
    }

    *{margin:0;padding:0;box-sizing:border-box;}

    body{
        background:var(--bg-primary);
        color:var(--text-primary);
        font-family:'Inter',sans-serif;
        line-height:1.5;
        min-height:100vh;
        overflow-x:hidden;
    }

    .container{
        max-width:1440px;
        margin:0 auto;
        padding:40px 32px;
    }

    /* ===== HEADER ===== */
    .page-header{
        display:flex;
        align-items:center;
        justify-content:space-between;
        margin-bottom:40px;
        padding-bottom:24px;
        border-bottom:2px solid var(--border);
        position:relative;
        flex-wrap:wrap;
        gap:16px;
    }

    .page-header::after{
        content:'';
        position:absolute;
        bottom:-2px;
        left:0;
        width:200px;
        height:2px;
        background:var(--text-primary);
    }

    .page-title h1{
        font-family:'Space Grotesk',sans-serif;
        font-size:36px;
        font-weight:700;
        letter-spacing:-2px;
        line-height:1.1;
        margin-bottom:6px;
    }

    .page-title p{
        color:var(--text-secondary);
        font-size:14px;
        font-weight:400;
    }

    .header-actions{
        display:flex;
        align-items:center;
        gap:12px;
        flex-wrap:wrap;
    }

    .back-btn{
        display:inline-flex;
        align-items:center;
        gap:8px;
        padding:10px 20px;
        border-radius:var(--radius-xs);
        background:var(--bg-secondary);
        border:2px solid var(--border);
        color:var(--text-secondary);
        text-decoration:none;
        font-size:13px;
        font-weight:600;
        transition:var(--transition);
    }

    .back-btn:hover{
        border-color:var(--border-light);
        color:var(--text-primary);
        transform:translateX(-4px);
    }

    .export-btn{
        display:inline-flex;
        align-items:center;
        gap:8px;
        padding:10px 20px;
        border-radius:var(--radius-xs);
        background:var(--success-soft);
        border:2px solid rgba(0,255,136,0.3);
        color:var(--success);
        text-decoration:none;
        font-size:13px;
        font-weight:600;
        transition:var(--transition);
        cursor:pointer;
        position:relative;
    }

    .export-btn:hover{
        background:var(--success);
        color:var(--bg-primary);
        border-color:var(--success);
    }

    .export-menu{
        display:none;
        position:absolute;
        top:calc(100% + 8px);
        right:0;
        background:var(--bg-secondary);
        border:2px solid var(--border);
        border-radius:var(--radius-xs);
        min-width:180px;
        z-index:100;
        overflow:hidden;
        box-shadow:var(--shadow-hover);
    }

    .export-menu.active{display:block;}

    .export-menu a{
        display:flex;
        align-items:center;
        gap:10px;
        padding:12px 16px;
        color:var(--text-secondary);
        text-decoration:none;
        font-size:13px;
        font-weight:500;
        transition:var(--transition);
    }

    .export-menu a:hover{
        background:var(--bg-hover);
        color:var(--text-primary);
    }

    .export-menu a i{width:16px;text-align:center;}

    /* ===== REVENUE CARD ===== */
    .revenue-section{
        margin-bottom:32px;
    }

    .revenue-card{
        background:var(--bg-secondary);
        border:2px solid var(--border);
        border-radius:var(--radius);
        padding:32px;
        transition:var(--transition);
        position:relative;
        overflow:hidden;
        display:flex;
        align-items:center;
        justify-content:space-between;
        flex-wrap:wrap;
        gap:20px;
    }

    .revenue-card::before{
        content:'';
        position:absolute;
        top:0;
        left:0;
        right:0;
        height:3px;
        background:var(--gold);
        opacity:0;
        transition:opacity 0.3s ease;
    }

    .revenue-card:hover{
        transform:translateY(-4px);
        border-color:var(--gold);
        box-shadow:var(--shadow-hover);
    }

    .revenue-card:hover::before{opacity:1;}

    .revenue-left{
        display:flex;
        align-items:center;
        gap:24px;
    }

    .revenue-icon{
        width:64px;
        height:64px;
        border-radius:var(--radius-sm);
        background:var(--gold-soft);
        border:2px solid rgba(255,215,0,0.3);
        display:flex;
        align-items:center;
        justify-content:center;
        font-size:28px;
        color:var(--gold);
        flex-shrink:0;
    }

    .revenue-card:hover .revenue-icon{
        background:var(--gold);
        color:var(--bg-primary);
        border-color:var(--gold);
    }

    .revenue-label{
        font-size:13px;
        color:var(--text-muted);
        font-weight:600;
        text-transform:uppercase;
        letter-spacing:1px;
        margin-bottom:6px;
    }

    .revenue-value{
        font-family:'Space Grotesk',sans-serif;
        font-size:42px;
        font-weight:700;
        letter-spacing:-2px;
        color:var(--gold);
        line-height:1;
    }

    .revenue-right{
        text-align:right;
    }

    .revenue-meta{
        font-size:12px;
        color:var(--text-muted);
    }

    /* ===== SECTION ===== */
    .section{
        background:var(--bg-secondary);
        border:2px solid var(--border);
        border-radius:var(--radius);
        padding:28px;
        transition:var(--transition);
        margin-bottom:24px;
    }

    .section:hover{
        border-color:var(--border-light);
        box-shadow:var(--shadow-hover);
    }

    .section-header{
        display:flex;
        align-items:center;
        justify-content:space-between;
        margin-bottom:24px;
        flex-wrap:wrap;
        gap:12px;
    }

    .section-title{
        font-family:'Space Grotesk',sans-serif;
        font-size:18px;
        font-weight:700;
        letter-spacing:-0.5px;
    }

    .section-action{
        font-size:12px;
        color:var(--text-muted);
        font-weight:600;
    }

    /* ===== FILTER BAR ===== */
    .filter-bar{
        display:flex;
        flex-wrap:wrap;
        gap:12px;
        margin-bottom:24px;
        align-items:end;
    }

    .filter-group{
        display:flex;
        flex-direction:column;
        gap:6px;
    }

    .filter-label{
        font-size:11px;
        font-weight:600;
        color:var(--text-muted);
        text-transform:uppercase;
        letter-spacing:0.5px;
    }

    .filter-input, .filter-select{
        padding:12px 16px;
        background:var(--bg-input);
        border:2px solid var(--border);
        border-radius:var(--radius-xs);
        color:var(--text-primary);
        font-family:'Inter',sans-serif;
        font-size:14px;
        outline:none;
        transition:var(--transition);
        min-width:180px;
    }

    .filter-input:focus, .filter-select:focus{
        border-color:var(--border-focus);
        background:var(--bg-tertiary);
    }

    .filter-input::placeholder{color:var(--text-muted);}

    /* Date input - proper styling */
    input[type="date"].filter-input{
        position:relative;
        cursor:pointer;
        padding-right:40px;
    }

    input[type="date"].filter-input::-webkit-calendar-picker-indicator{
        background:transparent;
        color:var(--text-muted);
        cursor:pointer;
        opacity:0.6;
        transition:opacity 0.2s;
    }

    input[type="date"].filter-input::-webkit-calendar-picker-indicator:hover{
        opacity:1;
    }

    .btn{
        display:inline-flex;
        align-items:center;
        justify-content:center;
        gap:8px;
        padding:12px 20px;
        border-radius:var(--radius-xs);
        font-family:'Inter',sans-serif;
        font-size:13px;
        font-weight:700;
        border:none;
        cursor:pointer;
        transition:var(--transition);
        text-decoration:none;
    }

    .btn-primary{
        background:var(--text-primary);
        color:var(--bg-primary);
    }

    .btn-primary:hover{
        transform:translateY(-2px);
        box-shadow:0 4px 20px rgba(255,255,255,0.2);
    }

    .btn-danger{
        background:transparent;
        color:var(--danger);
        border:2px solid rgba(255,68,68,0.3);
    }

    .btn-danger:hover{
        background:var(--danger);
        color:white;
        border-color:var(--danger);
    }

    .btn-icon{
        width:40px;
        height:40px;
        padding:0;
        border-radius:var(--radius-xs);
        background:var(--bg-tertiary);
        border:2px solid var(--border);
        color:var(--text-secondary);
        font-size:14px;
    }

    .btn-icon:hover{
        border-color:var(--border-light);
        color:var(--text-primary);
    }

    .btn-sm{padding:8px 14px;font-size:12px;}

    /* ===== SEARCH ===== */
    .search-wrapper{
        position:relative;
        flex:1;
        min-width:250px;
    }

    .search-wrapper i{
        position:absolute;
        left:14px;
        top:50%;
        transform:translateY(-50%);
        color:var(--text-muted);
        font-size:14px;
    }

    .search-wrapper .filter-input{
        padding-left:40px;
        width:100%;
    }

    /* ===== TABLE ===== */
    .table-box{
        overflow:hidden;
        border-radius:var(--radius-sm);
        border:2px solid var(--border);
        margin-bottom:20px;
    }

    table{
        width:100%;
        border-collapse:collapse;
    }

    thead th{
        background:var(--bg-tertiary);
        color:var(--text-secondary);
        padding:14px 16px;
        text-align:left;
        font-size:11px;
        font-weight:700;
        text-transform:uppercase;
        letter-spacing:1px;
        border-bottom:2px solid var(--border);
        cursor:pointer;
        user-select:none;
        transition:var(--transition);
        white-space:nowrap;
    }

    thead th:hover{
        color:var(--text-primary);
        background:var(--bg-hover);
    }

    thead th i{
        margin-left:6px;
        font-size:10px;
        opacity:0.5;
    }

    thead th.active-sort{
        color:var(--text-primary);
    }

    thead th.active-sort i{
        opacity:1;
    }

    tbody td{
        padding:14px 16px;
        border-bottom:1px solid var(--border);
        font-size:13px;
        vertical-align:middle;
    }

    tbody tr{
        transition:var(--transition);
    }

    tbody tr:hover{
        background:var(--bg-hover);
    }

    .user-cell{
        display:flex;
        align-items:center;
        gap:10px;
    }

    .user-avatar{
        width:36px;
        height:36px;
        border-radius:50%;
        background:var(--bg-input);
        border:2px solid var(--border);
        display:flex;
        align-items:center;
        justify-content:center;
        font-size:13px;
        color:var(--text-muted);
        font-weight:700;
        overflow:hidden;
        flex-shrink:0;
    }

    .user-avatar img{
        width:100%;
        height:100%;
        object-fit:cover;
    }

    .user-info{min-width:0;}

    .user-name{
        font-weight:700;
        color:var(--text-primary);
        white-space:nowrap;
        overflow:hidden;
        text-overflow:ellipsis;
    }

    .user-meta{
        font-size:11px;
        color:var(--text-muted);
    }

    .status-badge{
        display:inline-flex;
        align-items:center;
        gap:6px;
        padding:6px 14px;
        border-radius:100px;
        font-size:11px;
        font-weight:700;
        text-transform:uppercase;
        letter-spacing:0.5px;
        white-space:nowrap;
    }

    .status-paid{
        background:var(--success-soft);
        border:1px solid rgba(0,255,136,0.3);
        color:var(--success);
    }

    .status-pending{
        background:var(--warning-soft);
        border:1px solid rgba(255,170,0,0.3);
        color:var(--warning);
    }

    .status-expired{
        background:var(--danger-soft);
        border:1px solid rgba(255,68,68,0.3);
        color:var(--danger);
    }

    .price-tag{
        font-family:'Space Grotesk',sans-serif;
        font-weight:700;
        color:var(--gold);
    }

    .action-btns{
        display:flex;
        gap:6px;
    }

    .action-btns .btn-icon{
        width:32px;
        height:32px;
        font-size:12px;
    }

    /* ===== PAGINATION ===== */
    .pagination{
        display:flex;
        align-items:center;
        justify-content:space-between;
        flex-wrap:wrap;
        gap:16px;
    }

    .page-info{
        font-size:13px;
        color:var(--text-muted);
    }

    .page-info strong{
        color:var(--text-primary);
        font-weight:700;
    }

    .page-buttons{
        display:flex;
        gap:6px;
    }

    .page-btn{
        display:flex;
        align-items:center;
        justify-content:center;
        min-width:36px;
        height:36px;
        padding:0 12px;
        background:var(--bg-tertiary);
        border:2px solid var(--border);
        border-radius:var(--radius-xs);
        color:var(--text-secondary);
        font-family:'Inter',sans-serif;
        font-size:13px;
        font-weight:600;
        text-decoration:none;
        transition:var(--transition);
    }

    .page-btn:hover{
        border-color:var(--border-light);
        color:var(--text-primary);
        background:var(--bg-hover);
    }

    .page-btn.active{
        background:var(--text-primary);
        color:var(--bg-primary);
        border-color:var(--text-primary);
    }

    .page-btn.disabled{
        opacity:0.3;
        cursor:not-allowed;
        pointer-events:none;
    }

    /* ===== EMPTY STATE ===== */
    .empty-state{
        text-align:center;
        padding:60px 20px;
        color:var(--text-muted);
    }

    .empty-state i{
        font-size:48px;
        margin-bottom:16px;
        display:block;
        opacity:0.5;
    }

    .empty-state h3{
        font-family:'Space Grotesk',sans-serif;
        font-size:18px;
        color:var(--text-secondary);
        margin-bottom:8px;
    }

    /* ===== TOAST ===== */
    .toast-container{
        position:fixed;
        top:24px;
        right:24px;
        z-index:9999;
        display:flex;
        flex-direction:column;
        gap:12px;
    }

    .toast{
        background:var(--bg-secondary);
        border:2px solid var(--border);
        border-radius:var(--radius-sm);
        padding:16px 20px;
        display:flex;
        align-items:center;
        gap:12px;
        min-width:300px;
        max-width:400px;
        box-shadow:var(--shadow-hover);
        animation:slideIn 0.3s ease;
        transition:all 0.3s ease;
    }

    .toast.success{border-color:rgba(0,255,136,0.3);}
    .toast.error{border-color:rgba(255,68,68,0.3);}
    .toast.warning{border-color:rgba(255,170,0,0.3);}

    .toast-icon{
        width:36px;
        height:36px;
        border-radius:50%;
        display:flex;
        align-items:center;
        justify-content:center;
        font-size:16px;
        flex-shrink:0;
    }

    .toast.success .toast-icon{background:var(--success-soft);color:var(--success);}
    .toast.error .toast-icon{background:var(--danger-soft);color:var(--danger);}
    .toast.warning .toast-icon{background:var(--warning-soft);color:var(--warning);}

    .toast-content{flex:1;}

    .toast-title{
        font-weight:700;
        font-size:14px;
        margin-bottom:2px;
    }

    .toast-message{
        font-size:12px;
        color:var(--text-muted);
    }

    @keyframes slideIn{
        from{opacity:0;transform:translateX(40px);}
        to{opacity:1;transform:translateX(0);}
    }

    /* ===== DETAIL MODAL ===== */
    .modal-overlay{
        display:none;
        position:fixed;
        inset:0;
        background:rgba(0,0,0,0.8);
        backdrop-filter:blur(8px);
        z-index:1000;
        align-items:center;
        justify-content:center;
        padding:20px;
    }

    .modal-overlay.active{display:flex;}

    .modal-content{
        background:var(--bg-secondary);
        border:2px solid var(--border);
        border-radius:var(--radius);
        max-width:600px;
        width:100%;
        max-height:90vh;
        overflow-y:auto;
        position:relative;
        animation:fadeUp 0.3s ease;
    }

    .modal-header{
        display:flex;
        align-items:center;
        justify-content:space-between;
        padding:24px 28px;
        border-bottom:2px solid var(--border);
    }

    .modal-title{
        font-family:'Space Grotesk',sans-serif;
        font-size:20px;
        font-weight:700;
    }

    .modal-close{
        width:36px;
        height:36px;
        border-radius:50%;
        background:var(--bg-tertiary);
        border:2px solid var(--border);
        color:var(--text-secondary);
        display:flex;
        align-items:center;
        justify-content:center;
        cursor:pointer;
        transition:var(--transition);
        font-size:14px;
    }

    .modal-close:hover{
        background:var(--danger);
        color:white;
        border-color:var(--danger);
    }

    .modal-body{
        padding:28px;
    }

    .detail-grid{
        display:grid;
        grid-template-columns:repeat(2, 1fr);
        gap:20px;
    }

    @media(max-width:600px){
        .detail-grid{grid-template-columns:1fr;}
    }

    .detail-item{
        display:flex;
        flex-direction:column;
        gap:6px;
    }

    .detail-label{
        font-size:11px;
        font-weight:700;
        text-transform:uppercase;
        letter-spacing:1px;
        color:var(--text-muted);
    }

    .detail-value{
        font-size:15px;
        font-weight:600;
        color:var(--text-primary);
    }

    .detail-value.price{
        color:var(--gold);
        font-family:'Space Grotesk',sans-serif;
        font-size:18px;
    }

    .detail-divider{
        height:2px;
        background:var(--border);
        margin:20px 0;
        grid-column:1/-1;
    }

    .detail-status{
        display:inline-flex;
        align-items:center;
        gap:8px;
        padding:8px 16px;
        border-radius:100px;
        font-size:13px;
        font-weight:700;
        text-transform:uppercase;
    }

    /* ===== TODAY'S SCHEDULE - NEW STYLE ===== */
    .schedule-dates{
        display:flex;
        gap:12px;
        margin-bottom:24px;
        overflow-x:auto;
        padding-bottom:8px;
    }

    .date-tab{
        padding:12px 20px;
        background:var(--bg-tertiary);
        border:2px solid var(--border);
        border-radius:var(--radius-sm);
        cursor:pointer;
        transition:var(--transition);
        min-width:140px;
        text-align:center;
        user-select:none;
    }

    .date-tab:hover{
        border-color:var(--border-light);
    }

    .date-tab.active{
        background:var(--text-primary);
        border-color:var(--text-primary);
        color:var(--bg-primary);
    }

    .date-tab .date-day{
        font-size:11px;
        font-weight:700;
        text-transform:uppercase;
        letter-spacing:1px;
        margin-bottom:4px;
        opacity:0.7;
    }

    .date-tab .date-num{
        font-family:'Space Grotesk',sans-serif;
        font-size:18px;
        font-weight:700;
    }

    .date-tab .date-month{
        font-size:11px;
        opacity:0.7;
    }

    .schedule-barbers-grid{
        display:grid;
        grid-template-columns:repeat(auto-fill, minmax(280px, 1fr));
        gap:16px;
    }

    .schedule-barber-card{
        background:var(--bg-tertiary);
        border:2px solid var(--border);
        border-radius:var(--radius-sm);
        overflow:hidden;
        transition:var(--transition);
    }

    .schedule-barber-card:hover{
        border-color:var(--border-light);
        transform:translateY(-2px);
    }

    .schedule-barber-header{
        display:flex;
        align-items:center;
        gap:12px;
        padding:16px;
        background:var(--bg-input);
        border-bottom:2px solid var(--border);
    }

    .schedule-barber-avatar{
        width:44px;
        height:44px;
        border-radius:50%;
        object-fit:cover;
        border:2px solid var(--border);
        background:var(--bg-primary);
        display:flex;
        align-items:center;
        justify-content:center;
        font-size:16px;
        font-weight:700;
        color:var(--text-muted);
        flex-shrink:0;
        overflow:hidden;
    }

    .schedule-barber-avatar img{
        width:100%;
        height:100%;
        object-fit:cover;
    }

    .schedule-barber-info{flex:1;}

    .schedule-barber-name{
        font-family:'Space Grotesk',sans-serif;
        font-size:15px;
        font-weight:700;
        margin-bottom:2px;
    }

    .schedule-barber-role{
        font-size:11px;
        color:var(--text-muted);
    }

    .schedule-barber-status{
        padding:4px 10px;
        border-radius:100px;
        font-size:10px;
        font-weight:700;
        text-transform:uppercase;
    }

    .status-on{
        background:var(--success-soft);
        color:var(--success);
        border:1px solid rgba(0,255,136,0.3);
    }

    .status-off{
        background:var(--bg-input);
        color:var(--text-muted);
        border:1px solid var(--border);
    }

    .schedule-barber-body{
        padding:16px;
    }

    .schedule-slots{
        display:flex;
        flex-wrap:wrap;
        gap:8px;
    }

    .schedule-slot{
        padding:6px 12px;
        background:var(--bg-card);
        border:1px solid var(--border);
        border-radius:var(--radius-xs);
        font-size:12px;
        font-weight:600;
        transition:var(--transition);
    }

    .slot-booked{
        background:var(--success-soft);
        border-color:rgba(0,255,136,0.3);
        color:var(--success);
    }

    .slot-available{
        color:var(--text-muted);
    }

    .slot-empty{
        text-align:center;
        padding:20px;
        color:var(--text-muted);
        font-size:13px;
        width:100%;
    }

    /* ===== LOADING SPINNER ===== */
    .schedule-loading{
        grid-column:1/-1;
        text-align:center;
        padding:60px 20px;
        color:var(--text-muted);
    }

    .schedule-loading i{
        font-size:32px;
        margin-bottom:12px;
        display:block;
    }

    /* ===== ANIMATIONS ===== */
    @keyframes fadeUp{
        from{opacity:0;transform:translateY(20px);}
        to{opacity:1;transform:translateY(0);}
    }

    .revenue-card, .section{
        animation:fadeUp 0.5s ease forwards;
    }

    /* ===== SCROLLBAR ===== */
    ::-webkit-scrollbar{width:6px;}
    ::-webkit-scrollbar-track{background:var(--bg-primary);}
    ::-webkit-scrollbar-thumb{background:var(--border);border-radius:3px;}
    ::-webkit-scrollbar-thumb:hover{background:var(--border-light);}

    /* ===== RESPONSIVE ===== */
    @media(max-width:768px){
        .container{padding:20px 16px;}
        .page-title h1{font-size:28px;}
        .page-header{flex-direction:column;align-items:flex-start;}
        .header-actions{width:100%;}
        .back-btn, .export-btn{width:100%;justify-content:center;}
        .filter-bar{flex-direction:column;}
        .filter-group{width:100%;}
        .filter-input, .filter-select{width:100%;}
        .table-box{overflow-x:auto;}
        table{min-width:800px;}
        .revenue-card{flex-direction:column;align-items:flex-start;}
        .revenue-right{text-align:left;}
        .revenue-value{font-size:32px;}
        .detail-grid{grid-template-columns:1fr;}
    }
    </style>
</head>
<body>

<!-- TOAST CONTAINER -->
<div class="toast-container" id="toastContainer"></div>

<!-- DETAIL MODAL -->
<div class="modal-overlay" id="detailModal">
    <div class="modal-content">
        <div class="modal-header">
            <div class="modal-title">Booking Details</div>
            <button class="modal-close" onclick="closeModal()">
                <i class="fas fa-times"></i>
            </button>
        </div>
        <div class="modal-body" id="modalBody">
            <!-- Content loaded via JS -->
        </div>
    </div>
</div>

<div class="container">

    <!-- HEADER -->
    <div class="page-header">
        <div class="page-title">
            <h1>Bookings.</h1>
            <p>Manage and monitor all customer appointments</p>
        </div>
        <div class="header-actions">
            <a href="dashboard.php" class="back-btn">
                <i class="fas fa-arrow-left"></i> Back to Dashboard
            </a>
            <div style="position:relative;">
                <button class="export-btn" onclick="toggleExportMenu()">
                    <i class="fas fa-download"></i> Export Report
                    <i class="fas fa-chevron-down" style="margin-left:4px;font-size:10px;"></i>
                </button>
                <div class="export-menu" id="exportMenu">
                    <a href="#" onclick="doExport('excel')">
                        <i class="fas fa-file-excel" style="color:var(--success);"></i> Export Excel (.xls)
                    </a>
                    <a href="#" onclick="doExport('pdf')">
                        <i class="fas fa-file-pdf" style="color:var(--danger);"></i> Export PDF Report
                    </a>
                </div>
            </div>
        </div>
    </div>

    <!-- REVENUE -->
    <div class="revenue-section">
        <div class="revenue-card">
            <div class="revenue-left">
                <div class="revenue-icon">
                    <i class="fas fa-wallet"></i>
                </div>
                <div class="revenue-info">
                    <div class="revenue-label">Total Revenue</div>
                    <div class="revenue-value">Rp<?= number_format($stats['revenue'] ?? 0) ?></div>
                </div>
            </div>
            <div class="revenue-right">
                <div class="revenue-meta">
                    <?php if($status || $barber || $tanggal || $search): ?>
                    Based on active filters &bull; <?= $totalRows ?> booking(s)
                    <?php else: ?>
                    All time revenue from paid bookings
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>

    <!-- ALL BOOKINGS (NOW ON TOP) -->
    <div class="section" id="allBookings">
        <div class="section-header">
            <div class="section-title">All Bookings</div>
            <span class="section-action"><?= $totalRows ?> total record(s)</span>
        </div>

        <!-- FILTER BAR -->
        <form method="GET" action="booking.php#allBookings" id="filterForm">
            <div class="filter-bar">
                <div class="search-wrapper">
                    <i class="fas fa-search"></i>
                    <input type="text" class="filter-input" placeholder="Search user, package, or barber..." 
                           value="<?= htmlspecialchars($search) ?>" name="search"
                           id="searchInput">
                </div>
                
                <div class="filter-group">
                    <span class="filter-label">Status</span>
                    <select class="filter-select" name="status" onchange="document.getElementById('filterForm').submit()">
                        <option value="">Active (Hide Expired)</option>
                        <option value="paid" <?= $status=='paid'?'selected':'' ?>>Paid</option>
                        <option value="pending" <?= $status=='pending'?'selected':'' ?>>Pending</option>
                        <option value="expired" <?= $status=='expired'?'selected':'' ?>>Expired</option>
                        <option value="all" <?= $status=='all'?'selected':'' ?>>All Status</option>
                    </select>
                </div>
                
                <div class="filter-group">
                    <span class="filter-label">Barber</span>
                    <select class="filter-select" name="barber" onchange="document.getElementById('filterForm').submit()">
                        <option value="">All Barbers</option>
                        <?php mysqli_data_seek($dataBarber, 0); while($b = mysqli_fetch_assoc($dataBarber)): ?>
                        <option value="<?= $b['id'] ?>" <?= $barber==$b['id']?'selected':'' ?>><?= htmlspecialchars($b['nama']) ?></option>
                        <?php endwhile; ?>
                    </select>
                </div>
                
                <div class="filter-group">
                    <span class="filter-label">Date</span>
                    <input type="date" class="filter-input" name="tanggal" value="<?= $tanggal ?>" 
                           onchange="document.getElementById('filterForm').submit()"
                           id="dateFilterInput"
                           style="cursor:pointer;">
                </div>
                
                <a href="booking.php#allBookings" class="btn btn-danger btn-sm">
                    <i class="fas fa-undo"></i> Reset
                </a>
            </div>
        </form>

        <!-- TABLE -->
        <div class="table-box">
            <table>
                <thead>
                    <tr>
                        <th onclick="sortBy('id')">ID <?= sortIcon('id', $sort, $order) ?></th>
                        <th onclick="sortBy('username')">User <?= sortIcon('username', $sort, $order) ?></th>
                        <th onclick="sortBy('nama_paket')">Package <?= sortIcon('nama_paket', $sort, $order) ?></th>
                        <th onclick="sortBy('barber_nama')">Barber <?= sortIcon('barber_nama', $sort, $order) ?></th>
                        <th onclick="sortBy('tanggal')">Date <?= sortIcon('tanggal', $sort, $order) ?></th>
                        <th onclick="sortBy('jam')">Time <?= sortIcon('jam', $sort, $order) ?></th>
                        <th onclick="sortBy('harga')">Price <?= sortIcon('harga', $sort, $order) ?></th>
                        <th onclick="sortBy('status')">Status <?= sortIcon('status', $sort, $order) ?></th>
                        <th style="width:120px;">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if(mysqli_num_rows($q) > 0): ?>
                        <?php while($d = mysqli_fetch_assoc($q)): ?>
                        <tr>
                            <td style="font-family:'Space Grotesk',monospace;font-weight:600;">#<?= $d['id'] ?></td>
                            <td>
                                <div class="user-cell">
                                    <div class="user-avatar">
                                        <?php if(!empty($d['user_photo']) && file_exists('../'.$d['user_photo'])): ?>
                                        <img src="../<?= $d['user_photo'] ?>" alt="">
                                        <?php else: ?>
                                        <?= strtoupper(substr($d['username'],0,1)) ?>
                                        <?php endif; ?>
                                    </div>
                                    <div class="user-info">
                                        <div class="user-name"><?= !empty($d['username']) ? htmlspecialchars($d['username']) : 'Deleted User' ?></div>
                                        <div class="user-meta"><?= !empty($d['gender']) ? $d['gender'] : 'N/A' ?></div>
                                    </div>
                                </div>
                            </td>
                            <td><?= htmlspecialchars($d['nama_paket']) ?></td>
                            <td>
                                <div class="user-cell">
                                    <?php if(!empty($d['barber_foto'])): ?>
                                    <img src="upload/<?= $d['barber_foto'] ?>" alt="" style="width:28px;height:28px;border-radius:50%;object-fit:cover;border:2px solid var(--border);">
                                    <?php endif; ?>
                                    <?= htmlspecialchars($d['barber_nama']) ?>
                                </div>
                            </td>
                            <td><?= date('d M Y', strtotime($d['tanggal'])) ?></td>
                            <td style="font-family:'Space Grotesk',monospace;"><?= substr($d['jam'], 0, 5) ?></td>
                            <td class="price-tag">Rp<?= number_format($d['harga']) ?></td>
                            <td>
                                <?php if($d['status'] == 'paid'): ?>
                                <span class="status-badge status-paid"><i class="fas fa-check"></i> Paid</span>
                                <?php elseif($d['status'] == 'pending'): ?>
                                <span class="status-badge status-pending"><i class="fas fa-clock"></i> Pending</span>
                                <?php else: ?>
                                <span class="status-badge status-expired"><i class="fas fa-times"></i> Expired</span>
                                <?php endif; ?>
                            </td>
                            <td>
                                <div class="action-btns">
                                    <button class="btn btn-icon" onclick="showDetail(<?= $d['id'] ?>)" title="View Details">
                                        <i class="fas fa-eye"></i>
                                    </button>
                                    <?php if($d['status'] == 'pending'): ?>
                                    <a href="proses_update_status.php?id=<?= $d['id'] ?>&status=paid&redirect=<?= urlencode($_SERVER['QUERY_STRING'].'#allBookings') ?>" 
                                       class="btn btn-icon" style="color:var(--success);border-color:rgba(0,255,136,0.2);" title="Mark as Paid">
                                        <i class="fas fa-check"></i>
                                    </a>
                                    <?php endif; ?>
                                </div>
                            </td>
                        </tr>
                        <?php endwhile; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="9">
                                <div class="empty-state">
                                    <i class="fas fa-calendar-times"></i>
                                    <h3>No bookings found</h3>
                                    <p>Try adjusting your filters or search criteria.</p>
                                </div>
                            </td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>

        <!-- PAGINATION -->
        <?php if($totalPages > 1): ?>
        <div class="pagination">
            <div class="page-info">
                Showing <strong><?= $offset + 1 ?>-<?= min($offset + $perPage, $totalRows) ?></strong> of <strong><?= $totalRows ?></strong> records
            </div>
            <div class="page-buttons">
                <?php 
                $baseParams = array_diff_key($_GET, array_flip(['page']));
                $baseUrl = "booking.php?".http_build_query($baseParams);
                $baseUrl .= (strpos($baseUrl, '?') === false ? '?' : '&');
                
                if($page > 1): 
                ?>
                <a href="<?= $baseUrl ?>page=<?= $page-1 ?>#allBookings" class="page-btn"><i class="fas fa-chevron-left"></i></a>
                <?php else: ?>
                <span class="page-btn disabled"><i class="fas fa-chevron-left"></i></span>
                <?php endif; ?>
                
                <?php 
                $startPage = max(1, $page - 2);
                $endPage = min($totalPages, $page + 2);
                
                if($startPage > 1) echo '<span class="page-btn disabled">...</span>';
                
                for($i = $startPage; $i <= $endPage; $i++): 
                ?>
                <a href="<?= $baseUrl ?>page=<?= $i ?>#allBookings" class="page-btn <?= $i==$page?'active':'' ?>"><?= $i ?></a>
                <?php endfor; 
                
                if($endPage < $totalPages) echo '<span class="page-btn disabled">...</span>';
                ?>
                
                <?php if($page < $totalPages): ?>
                <a href="<?= $baseUrl ?>page=<?= $page+1 ?>#allBookings" class="page-btn"><i class="fas fa-chevron-right"></i></a>
                <?php else: ?>
                <span class="page-btn disabled"><i class="fas fa-chevron-right"></i></span>
                <?php endif; ?>
            </div>
        </div>
        <?php endif; ?>
    </div>

    <!-- TODAY'S SCHEDULE (NOW BELOW - AJAX Powered) -->
    <div class="section" id="todaySchedule">
        <div class="section-header">
            <div class="section-title">
                <i class="fas fa-calendar-alt" style="margin-right:8px;"></i>
                Barber Schedule
            </div>
            <span class="section-action">Next 7 days availability</span>
        </div>
        
        <!-- Date Tabs -->
        <div class="schedule-dates">
            <?php foreach($dates as $idx => $date): ?>
            <div class="date-tab <?= $date['full'] == $activeScheduleDate ? 'active' : '' ?>" 
                 onclick="switchDate('<?= $date['full'] ?>', this)"
                 data-date="<?= $date['full'] ?>">
                <div class="date-day"><?= $date['is_today'] ? 'Today' : $date['day'] ?></div>
                <div class="date-num"><?= date('d', strtotime($date['full'])) ?></div>
                <div class="date-month"><?= date('M', strtotime($date['full'])) ?></div>
            </div>
            <?php endforeach; ?>
        </div>

        <!-- Schedule Grid -->
        <div class="schedule-barbers-grid" id="scheduleGrid">
            <?php
            // Initial load - show only ON DUTY barbers for today
            $hasAnySchedule = false;
            
            mysqli_data_seek($allBarbers, 0);
            while($barberRow = mysqli_fetch_assoc($allBarbers)){
                $bid = $barberRow['id'];
                $key = $activeScheduleDate."_".$bid;
                $isOnDuty = in_array($key, $jadwal);
                
                // ONLY SHOW IF ON DUTY
                if(!$isOnDuty) continue;
                
                $hasAnySchedule = true;
                
                // Get bookings for this barber on this date
                $bookingsQuery = "
                    SELECT b.*, u.username, p.nama_paket, p.harga
                    FROM booking b
                    JOIN users u ON b.user_id = u.id
                    JOIN paket p ON b.paket_id = p.id
                    WHERE b.barber_id = $bid AND b.tanggal = '$activeScheduleDate' AND b.status = 'paid'
                    ORDER BY b.jam ASC
                ";
                $bookingsResult = mysqli_query($conn, $bookingsQuery);
                $hasBookings = mysqli_num_rows($bookingsResult) > 0;
            ?>
            <div class="schedule-barber-card" data-date="<?= $activeScheduleDate ?>">
                <div class="schedule-barber-header">
                    <div class="schedule-barber-avatar">
                        <?php if(!empty($barberRow['foto'])): ?>
                        <img src="upload/<?= $barberRow['foto'] ?>" alt="<?= htmlspecialchars($barberRow['nama']) ?>">
                        <?php else: ?>
                        <?= strtoupper(substr($barberRow['nama'],0,1)) ?>
                        <?php endif; ?>
                    </div>
                    <div class="schedule-barber-info">
                        <div class="schedule-barber-name"><?= htmlspecialchars($barberRow['nama']) ?></div>
                        <div class="schedule-barber-role">On Duty</div>
                    </div>
                    <span class="schedule-barber-status status-on">Available</span>
                </div>
                <div class="schedule-barber-body">
                    <?php if($hasBookings): ?>
                    <div class="schedule-slots">
                        <?php while($bk = mysqli_fetch_assoc($bookingsResult)): ?>
                        <div class="schedule-slot slot-booked">
                            <i class="fas fa-check-circle" style="margin-right:4px;"></i>
                            <?= substr($bk['jam'], 0, 5) ?> - <?= htmlspecialchars($bk['username']) ?>
                        </div>
                        <?php endwhile; ?>
                    </div>
                    <?php else: ?>
                    <div class="schedule-slots">
                        <div class="slot-empty">No bookings yet - Available for walk-in</div>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
            <?php } ?>
            
                        <?php if(!$hasAnySchedule): ?>
            <div style="grid-column:1/-1;text-align:center;padding:40px;color:var(--text-muted);">
                <i class="fas fa-calendar-day" style="font-size:48px;margin-bottom:16px;display:block;opacity:0.5;"></i>
                <h3 style="font-family:'Space Grotesk',sans-serif;font-size:18px;color:var(--text-secondary);margin-bottom:8px;">No barbers on duty</h3>
                <p>No barbers are scheduled for <?= date('d M Y', strtotime($activeScheduleDate)) ?>.</p>
            </div>
            <?php endif; ?>
        </div>
    </div>

</div>

<script>
// ===== SCROLL POSITION MANAGEMENT =====
(function(){
    window.addEventListener('beforeunload', function(){
        sessionStorage.setItem('booking_scrollY', window.scrollY);
    });
    
    window.addEventListener('load', function(){
        const savedY = sessionStorage.getItem('booking_scrollY');
        if(savedY !== null){
            window.scrollTo(0, parseInt(savedY));
            sessionStorage.removeItem('booking_scrollY');
        }
        
        if(window.location.hash){
            const el = document.querySelector(window.location.hash);
            if(el){
                setTimeout(() => {
                    el.scrollIntoView({behavior:'smooth', block:'start'});
                }, 100);
            }
        }
    });
})();

// ===== FLASH TOAST =====
<?php if($flash): ?>
showToast('<?= $flash['type'] ?>', '<?= addslashes($flash['title']) ?>', '<?= addslashes($flash['message']) ?>');
<?php endif; ?>

function showToast(type, title, message){
    const container = document.getElementById('toastContainer');
    const toast = document.createElement('div');
    toast.className = `toast ${type}`;
    
    const icons = {
        success: 'fa-check-circle',
        error: 'fa-times-circle',
        warning: 'fa-exclamation-circle',
        info: 'fa-info-circle'
    };
    
    toast.innerHTML = `
        <div class="toast-icon"><i class="fas ${icons[type] || icons.success}"></i></div>
        <div class="toast-content">
            <div class="toast-title">${title}</div>
            <div class="toast-message">${message}</div>
        </div>
    `;
    
    container.appendChild(toast);
    
    setTimeout(() => {
        toast.style.opacity = '0';
        toast.style.transform = 'translateX(40px)';
        setTimeout(() => toast.remove(), 300);
    }, 4000);
}

// ===== EXPORT MENU =====
function toggleExportMenu(){
    document.getElementById('exportMenu').classList.toggle('active');
}

function doExport(type){
    const params = new URLSearchParams(window.location.search);
    params.set('export', type);
    window.location.href = 'booking.php?' + params.toString();
}

document.addEventListener('click', function(e){
    if(!e.target.closest('.export-btn') && !e.target.closest('.export-menu')){
        document.getElementById('exportMenu').classList.remove('active');
    }
});

// ===== SEARCH FIX =====
const searchInput = document.getElementById('searchInput');

// Search only submits on Enter key, NOT on typing
searchInput.addEventListener('keydown', function(e){
    if(e.key === 'Enter'){
        e.preventDefault();
        document.getElementById('filterForm').submit();
    }
});

// ===== DATE FILTER - CLICK ANYWHERE TO OPEN =====
const dateInput = document.getElementById('dateFilterInput');
if(dateInput){
    // Click anywhere on the input to open date picker
    dateInput.addEventListener('click', function(e){
        // Only trigger if not clicking the calendar icon directly
        if(e.offsetX < this.offsetWidth - 40){
            this.showPicker();
        }
    });
}

// ===== SORTING =====
function sortBy(col){
    sessionStorage.setItem('booking_scrollY', window.scrollY);
    
    const params = new URLSearchParams(window.location.search);
    const currentSort = params.get('sort') || 'tanggal';
    const currentOrder = params.get('order') || 'DESC';
    
    if(currentSort === col){
        params.set('order', currentOrder === 'ASC' ? 'DESC' : 'ASC');
    } else {
        params.set('sort', col);
        params.set('order', 'ASC');
    }
    
    window.location.href = 'booking.php?' + params.toString() + '#allBookings';
}

// ===== DETAIL MODAL =====
function showDetail(id){
    const modal = document.getElementById('detailModal');
    const modalBody = document.getElementById('modalBody');
    
    modalBody.innerHTML = `
        <div style="text-align:center;padding:40px;">
            <i class="fas fa-spinner fa-spin" style="font-size:24px;color:var(--text-muted);"></i>
            <p style="margin-top:16px;color:var(--text-muted);">Loading details...</p>
        </div>
    `;
    
    modal.classList.add('active');
    
    // Fetch actual data via AJAX
    fetch('booking.php?ajax_detail=' + id)
        .then(response => response.json())
        .then(data => {
            if(data.error){
                modalBody.innerHTML = `<div style="text-align:center;padding:40px;color:var(--danger);">Error: ${data.error}</div>`;
                return;
            }
            
            const statusColors = {
                'paid': {bg: 'var(--success-soft)', color: 'var(--success)', border: 'rgba(0,255,136,0.3)', icon: 'fa-check'},
                'pending': {bg: 'var(--warning-soft)', color: 'var(--warning)', border: 'rgba(255,170,0,0.3)', icon: 'fa-clock'},
                'expired': {bg: 'var(--danger-soft)', color: 'var(--danger)', border: 'rgba(255,68,68,0.3)', icon: 'fa-times'}
            };
            const sc = statusColors[data.status] || statusColors['pending'];
            
            modalBody.innerHTML = `
                <div class="detail-grid">
                    <div class="detail-item">
                        <div class="detail-label">Booking ID</div>
                        <div class="detail-value">#${data.id}</div>
                    </div>
                    <div class="detail-item">
                        <div class="detail-label">Status</div>
                        <div class="detail-value">
                            <span class="detail-status" style="background:${sc.bg};color:${sc.color};border:1px solid ${sc.border};">
                                <i class="fas ${sc.icon}" style="margin-right:6px;"></i>${data.status.toUpperCase()}
                            </span>
                        </div>
                    </div>
                    <div class="detail-divider"></div>
                    <div class="detail-item">
                        <div class="detail-label">Customer</div>
                        <div class="detail-value">${data.username}</div>
                    </div>
                    <div class="detail-item">
                        <div class="detail-label">Email</div>
                        <div class="detail-value">${data.email || 'N/A'}</div>
                    </div>
                    <div class="detail-item">
                        <div class="detail-label">Phone</div>
                        <div class="detail-value">${data.phone || 'N/A'}</div>
                    </div>
                    <div class="detail-item">
                        <div class="detail-label">Gender</div>
                        <div class="detail-value">${data.gender || 'N/A'}</div>
                    </div>
                    <div class="detail-divider"></div>
                    <div class="detail-item">
                        <div class="detail-label">Package</div>
                        <div class="detail-value">${data.nama_paket}</div>
                    </div>
                    <div class="detail-item">
                        <div class="detail-label">Price</div>
                        <div class="detail-value price">Rp${data.harga_formatted}</div>
                    </div>
                    <div class="detail-item">
                        <div class="detail-label">Barber</div>
                        <div class="detail-value">${data.barber_nama}</div>
                    </div>
                    <div class="detail-item">
                        <div class="detail-label">Date & Time</div>
                        <div class="detail-value">${data.tanggal_formatted} • ${data.jam}</div>
                    </div>
                    <div class="detail-divider"></div>
                    <div class="detail-item" style="grid-column:1/-1;">
                        <div class="detail-label">Booked At</div>
                        <div class="detail-value">${data.created_at}</div>
                    </div>
                </div>
            `;
        })
        .catch(err => {
            modalBody.innerHTML = `<div style="text-align:center;padding:40px;color:var(--danger);">Failed to load details</div>`;
        });
}

function closeModal(){
    document.getElementById('detailModal').classList.remove('active');
}

// Close modal on overlay click
document.getElementById('detailModal').addEventListener('click', function(e){
    if(e.target === this){
        closeModal();
    }
});

// Close modal on Escape key
document.addEventListener('keydown', function(e){
    if(e.key === 'Escape'){
        closeModal();
        document.getElementById('exportMenu').classList.remove('active');
    }
});

// ===== DATE TAB SWITCHING - AJAX =====
function switchDate(dateStr, tabEl){
    // Update active tab UI
    document.querySelectorAll('.date-tab').forEach(t => t.classList.remove('active'));
    tabEl.classList.add('active');
    
    // Show loading
    const grid = document.getElementById('scheduleGrid');
    grid.innerHTML = `
        <div class="schedule-loading">
            <i class="fas fa-spinner fa-spin"></i>
            <p>Loading schedule...</p>
        </div>
    `;
    
    // Fetch via AJAX
    fetch('booking.php?ajax_schedule=1&schedule_date=' + dateStr)
        .then(response => response.text())
        .then(html => {
            grid.innerHTML = html;
            showToast('info', 'Schedule Updated', 'Showing barbers on duty for ' + dateStr);
        })
        .catch(err => {
            grid.innerHTML = `
                <div style="grid-column:1/-1;text-align:center;padding:40px;color:var(--text-muted);">
                    <i class="fas fa-exclamation-circle" style="font-size:48px;margin-bottom:16px;display:block;opacity:0.5;"></i>
                    <h3 style="font-family:'Space Grotesk',sans-serif;font-size:18px;color:var(--text-secondary);margin-bottom:8px;">Failed to load</h3>
                    <p>Please refresh the page.</p>
                </div>
            `;
        });
}

// ===== KEYBOARD SHORTCUTS =====
document.addEventListener('keydown', function(e){
    if(e.ctrlKey && e.key === 'f'){
        e.preventDefault();
        document.getElementById('searchInput').focus();
    }
});
</script>

</body>
</html>